# .github/drafter-config.yaml

# Draft release 형식
version-template: "$MAJOR.$MINOR.$PATCH"
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
commitish: main

# 변경사항 그룹화 (구분)
categories:
  - title: "새 기능"
    labels:
      - "new"
  - title: "기능 개선"
    labels:
      - "feature"
  - title: "수정 사항"
    labels:
      - "modified"
  - title: "오류 수정"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "지원 중단"
    labels:
      - "deprecated"

exclude-labels:
  - "skip-changelog"

# 커스텀 change 포맷
change-template: "- **$TITLE**"
change-title-escapes: '\<*_&'

# 레이블 기반 버전 bump 규칙
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

replacers:
  # [ABC], [FEAT], [FIX] 등의 모든 대괄호 접두어 제거
  - search: '/\[[A-Za-z0-9_-]+\]\s*/g'
    replace: ""

# 최종 Release Notes 템플릿
template: |
  # 버전 $RESOLVED_VERSION
  _발행일: RELEASE_DATE_PLACEHOLDER_  

  ## 변경 내역
  $CHANGES
